apiVersion: v1
kind: ReplicationController
metadata:
  name: cpr
spec:
  replicas: 1
  selector:
    name: cpr
  template:
    metadata:
      labels:
        name: cpr
    spec:
      containers:
      - name: im
        image: indigodatacloud/cloudproviderranker
        ports:
        - containerPort: 8080
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: cpr
  labels:
    name: cpr
spec:
  type: ClusterIP
  ports:
  - name: cpr-http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: cpr
