#!/bin/sh

java_name=java
java_path=/usr/bin/${java_name}
pid_file=/var/run/CloudProviderRanker.pid
logfile=/var/log/CloudProviderRanker.log
jar_name=CloudProviderRanker-jar-with-dependencies.jar
jar_path=/usr/share/java/cpr

running()
{
   pid=`ps -ef|grep ${java_name}|grep CloudProviderRanker|awk '{print $2}'`

    if [ -z "${pid}" ]; then
        return 1
    fi

    return 0
}

ret_code=0

start()
{
    echo -n "starting CloudProviderRanker... "
    if running; then
        echo "ok (already running)"
    else
        mkdir -p /var/run/
        rm -f ${pid_file}
        touch ${pid_file}
        touch ${logfile}
        su root -c "${java_path} -jar ${jar_path}/${jar_name} -p 8443 -r ${jar_path}/DefaultRules.drl ${jar_path}/sla_priorities.json ${jar_path}/paasmetric_normalization.json >> /var/log/CloudProviderRanker.log 2>&1 &"
        sleep 2
        local pid=`ps -ef|grep ${java_name}|grep CloudProviderRanker|awk '{print $2}'`
        echo $pid > ${pid_file}

        sleep 1
        if running; then
            echo "ok"
        else
            echo "failure"
            ret_code=1
        fi
    fi
}

stop()
{
    if running; then
        echo -n "stopping CloudProviderRanker... "
        pid=`ps -ef|grep java|grep CloudProviderRanker|awk '{print $2}'`
        kill $pid
        sleep 1
        echo "ok"
        rm -f ${pid_file}
    fi
    return
}

status()
{
    running
    RETVAL=$?
    if [ ${RETVAL} -eq 0 ]; then
        pid=`ps -ef|grep java|grep CloudProviderRanker|awk '{print $2}'`
        echo "CloudProviderRanker (pid ${pid}) is running..."
    else
        echo "CloudProviderRanker is not running"
    fi
    return ${RETVAL}
}

usage()
{
    echo "Usage: ${this_script_name} {start|stop|restart|status}"
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        if [ ${ret_code} -eq 0 ]; then
            start
        fi
        ;;
    status)
        status
        ret_code=$?
        ;;
    *)
        usage
        ret_code=1
esac

exit ${ret_code}
