package org.indigo.cloudproviderruleengine;
 
import org.indigo.cloudproviderruleengine.CloudProvider;

rule "VEPHDISK"
	when
		cp : CloudProvider( inUseVEPHDISK < totalVEPHDISK )
	then
		cp.addToTotalRank( ((double)(cp.getTotalVEPHDISK() - cp.getInUseVEPHDISK())) /((double) cp.getTotalVEPHDISK()) );
end

rule "VDISK"
	when
		cp : CloudProvider( inUseVDISK < totalVDISK )
	then
		cp.addToTotalRank( ((double)(cp.getTotalVDISK() - cp.getInUseVDISK())) /((double) cp.getTotalVDISK()) );
end

rule "VCPU"
    when
        cp : CloudProvider( inUseVCPU < totalVCPU )
    then
        cp.addToTotalRank( ((double)(cp.getTotalVCPU() - cp.getInUseVCPU()))/((double)cp.getTotalVCPU()) );
end

rule "VRAM"
	when 
		cp : CloudProvider( inUseVRAM < totalVRAM )
	then
		cp.addToTotalRank( ((double)(cp.getTotalVRAM()-cp.getInUseVRAM()))/((double)cp.getTotalVRAM()) );
end

rule "ZERO"
    when
	cp : CloudProvider( inUseVCPU >= totalVCPU || inUseVRAM >= totalVRAM || inUseVEPHDISK >= totalVEPHDISK || inUseVDISK >= totalVDISK  )
    then
	cp.zeroRank( );
end